# NRC Word-Emotion Association Lexicon (subset)
# Based on Saif Mohammad & Peter Turney — NRC Canada

NRC_LEXICON = {
    "abandon": ["fear","sadness"], "abhor": ["anger","disgust"],
    "abhorrent": ["anger","disgust"], "abuse": ["anger","disgust","sadness"],
    "accomplish": ["joy","anticipation","trust"], "achievement": ["joy","anticipation"],
    "admire": ["joy","trust"], "adore": ["joy","trust"],
    "adventure": ["anticipation","joy","surprise"], "afraid": ["fear","sadness"],
    "aggression": ["anger"], "agony": ["sadness","fear"],
    "alarm": ["fear","surprise"], "amazing": ["joy","surprise"],
    "anger": ["anger"], "anguish": ["sadness","fear"],
    "annoy": ["anger","disgust"], "anxiety": ["fear","sadness"],
    "appalled": ["disgust","anger","surprise"], "appreciate": ["joy","trust"],
    "aspire": ["anticipation","joy"], "astound": ["surprise","joy"],
    "attack": ["anger","fear"], "awe": ["surprise","joy","trust"],
    "awful": ["sadness","disgust"], "bad": ["sadness","disgust"],
    "beautiful": ["joy","trust"], "beloved": ["joy","trust"],
    "bereave": ["sadness"], "bereavement": ["sadness","fear"],
    "betrayal": ["anger","sadness","disgust"], "bewildered": ["surprise","fear"],
    "bliss": ["joy","trust"], "bold": ["anticipation","trust"],
    "boring": ["sadness","disgust"], "brave": ["anticipation","trust","joy"],
    "bravery": ["trust","anticipation"], "calm": ["trust","joy"],
    "catastrophe": ["fear","sadness","surprise"], "celebrate": ["joy","anticipation"],
    "chaos": ["fear","anger","surprise"], "charm": ["joy","trust"],
    "cheat": ["anger","disgust","sadness"], "cheerful": ["joy"],
    "comfort": ["joy","trust"], "compassion": ["trust","sadness","joy"],
    "confident": ["trust","anticipation","joy"], "confusion": ["fear","surprise"],
    "courageous": ["trust","anticipation"], "crime": ["anger","disgust","fear"],
    "cruel": ["disgust","anger","sadness"], "curious": ["anticipation","surprise","joy"],
    "danger": ["fear","anticipation"], "death": ["sadness","fear"],
    "deceit": ["disgust","anger"], "defeat": ["sadness","anger"],
    "depressed": ["sadness"], "depression": ["sadness","fear"],
    "desperate": ["fear","sadness","anticipation"], "destroy": ["anger","sadness"],
    "devastated": ["sadness","surprise"], "devoted": ["joy","trust"],
    "dirty": ["disgust"], "disappoint": ["sadness","anger"],
    "disaster": ["fear","sadness","surprise"], "distress": ["sadness","fear"],
    "doubt": ["fear","sadness"], "dreadful": ["fear","disgust"],
    "ecstasy": ["joy","surprise"], "effective": ["trust","anticipation"],
    "empathy": ["trust","sadness","joy"], "encourage": ["trust","anticipation","joy"],
    "enjoy": ["joy","anticipation"], "enlighten": ["surprise","trust","anticipation"],
    "enthusiasm": ["joy","anticipation"], "excited": ["joy","anticipation","surprise"],
    "exhausted": ["sadness"], "fail": ["sadness","anger"],
    "faithful": ["trust","joy"], "fantastic": ["joy","surprise"],
    "fear": ["fear"], "fearful": ["fear","sadness"],
    "fierce": ["anger","anticipation"], "forgive": ["trust","joy"],
    "fraud": ["disgust","anger"], "free": ["joy","anticipation","trust"],
    "friendly": ["trust","joy"], "frightened": ["fear","surprise"],
    "frustrated": ["anger","sadness"], "fun": ["joy","anticipation"],
    "funny": ["joy","surprise"], "gentle": ["trust","joy"],
    "glad": ["joy"], "glory": ["joy","trust","anticipation"],
    "good": ["joy","trust"], "graceful": ["joy","trust"],
    "grateful": ["joy","trust"], "great": ["joy","anticipation"],
    "grief": ["sadness","fear"], "growth": ["anticipation","joy","trust"],
    "guilty": ["sadness","fear"], "happiness": ["joy"],
    "happy": ["joy"], "harm": ["anger","sadness","fear"],
    "hate": ["anger","disgust"], "helpless": ["sadness","fear"],
    "heroic": ["trust","joy","anticipation"], "hopeful": ["anticipation","joy","trust"],
    "hopeless": ["sadness","fear"], "horrible": ["disgust","fear","sadness"],
    "hostile": ["anger","disgust"], "humble": ["trust","joy"],
    "hurt": ["sadness","anger"], "ignorant": ["anger","disgust"],
    "injustice": ["anger","sadness","disgust"], "inspire": ["joy","anticipation","trust"],
    "insult": ["anger","disgust","sadness"], "jealous": ["anger","sadness","disgust"],
    "joyful": ["joy"], "joyous": ["joy","surprise"],
    "jubilant": ["joy","surprise"], "kind": ["trust","joy"],
    "kindness": ["trust","joy"], "lazy": ["disgust","sadness"],
    "lonely": ["sadness"], "love": ["joy","trust","anticipation"],
    "loyal": ["trust","joy"], "magnificent": ["joy","surprise","trust"],
    "manipulate": ["anger","disgust"], "melancholy": ["sadness"],
    "miracle": ["surprise","joy","trust"], "miserable": ["sadness"],
    "motivated": ["anticipation","joy","trust"], "mourning": ["sadness","fear"],
    "neglect": ["sadness","anger","disgust"], "nervous": ["fear"],
    "nightmare": ["fear","sadness"], "optimistic": ["anticipation","joy","trust"],
    "outstanding": ["joy","surprise","trust"], "overwhelmed": ["fear","surprise","sadness"],
    "panic": ["fear","surprise"], "passionate": ["joy","anticipation","trust"],
    "patience": ["trust","anticipation"], "peaceful": ["joy","trust"],
    "pessimistic": ["sadness","fear"], "powerful": ["trust","anticipation","joy"],
    "prejudice": ["disgust","anger"], "pride": ["joy","trust","anticipation"],
    "purposeful": ["anticipation","trust"], "rage": ["anger"],
    "regret": ["sadness"], "rejected": ["sadness","anger"],
    "resilient": ["trust","anticipation"], "respect": ["trust","joy"],
    "restore": ["trust","anticipation","joy"], "ruin": ["sadness","anger","disgust"],
    "sad": ["sadness"], "sadness": ["sadness"],
    "selfish": ["disgust","anger"], "shame": ["sadness","fear","disgust"],
    "shocked": ["surprise","fear"], "sincere": ["trust"],
    "sorrow": ["sadness"], "stable": ["trust"],
    "stress": ["fear","anger","sadness"], "struggle": ["sadness","fear","anger"],
    "success": ["joy","trust","anticipation"], "suffering": ["sadness","fear"],
    "support": ["trust","joy"], "surprise": ["surprise"],
    "terror": ["fear"], "thankful": ["joy","trust"],
    "thoughtful": ["trust","anticipation"], "toxic": ["disgust","anger","sadness"],
    "tragedy": ["sadness","fear"], "trust": ["trust"],
    "truthful": ["trust"], "uncertain": ["fear","anticipation"],
    "unfair": ["anger","sadness","disgust"], "upset": ["sadness","anger"],
    "valuable": ["trust","anticipation"], "victorious": ["joy","anticipation","trust"],
    "violence": ["anger","fear","disgust"], "vulnerable": ["fear","sadness"],
    "warmth": ["joy","trust"], "wonderful": ["joy","surprise","trust"],
    "worry": ["fear","sadness"], "worthless": ["sadness","disgust"],
    "zealous": ["anticipation","anger"],
}

EMOTION_META = {
    "joy":          {"emoji": "😊", "color": "#f9d71c", "label": "Joy"},
    "sadness":      {"emoji": "😢", "color": "#74b9ff", "label": "Sadness"},
    "anger":        {"emoji": "😡", "color": "#ff4757", "label": "Anger"},
    "fear":         {"emoji": "😨", "color": "#a29bfe", "label": "Fear"},
    "disgust":      {"emoji": "🤢", "color": "#55efc4", "label": "Disgust"},
    "surprise":     {"emoji": "😮", "color": "#fd79a8", "label": "Surprise"},
    "trust":        {"emoji": "🤝", "color": "#00cec9", "label": "Trust"},
    "anticipation": {"emoji": "⏳", "color": "#e17055", "label": "Anticipation"},
}
