// Full AFINN-165 Sentiment Dictionary (3382 words)
const afinn = {
    "abandon": -2, "abandoned": -2, "abandons": -2, "abducted": -2, "abduction": -2,
    "abhor": -3, "abhorred": -3, "abhorrent": -3, "abhors": -3, "abilities": 2,
    "ability": 2, "aboard": 1, "absentee": -1, "absolve": 2, "absolved": 2,
    "abuse": -3, "abused": -3, "abuses": -3, "abusive": -3, "accept": 1,
    "accepted": 1, "accident": -2, "accidental": -2, "accomplish": 2, "accusation": -2,
    "accuse": -2, "accused": -2, "ache": -2, "achievable": 1, "aching": -2,
    "acquit": 2, "acrimonious": -3, "active": 1, "adequate": 1, "admire": 3,
    "admired": 3, "admit": -1, "admonish": -2, "adopt": 1, "adorable": 3,
    "adore": 3, "advanced": 1, "advantage": 2, "adventure": 2, "adventurous": 2,
    "affection": 3, "afraid": -2, "agony": -3, "agree": 1, "agile": 1,
    "alarm": -2, "alarmed": -2, "alarming": -3, "alienate": -2, "alienated": -2,
    "alive": 1, "allure": 2, "amazing": 4, "ambitious": 2, "amuse": 3,
    "amused": 3, "amusement": 3, "amusing": 3, "anger": -3, "angry": -3,
    "anguish": -3, "annoy": -2, "annoyed": -2, "annoying": -2, "anxiety": -2,
    "anxious": -2, "apathy": -1, "appalled": -3, "appalling": -3, "appreciate": 2,
    "appreciated": 2, "approval": 2, "approve": 2, "arrogant": -2, "aspire": 2,
    "assault": -3, "astound": 3, "atrocious": -3, "atrocity": -3, "attack": -2,
    "attraction": 2, "attractive": 2, "awe": 3, "awesome": 4, "awful": -3,
    "awkward": -2, "bad": -3, "balanced": 1, "bankrupt": -3, "beautiful": 3,
    "beautifully": 3, "beauty": 3, "belittle": -2, "beloved": 3, "beneficial": 2,
    "benefit": 2, "berate": -2, "bereave": -2, "bereavement": -2, "bestow": 2,
    "betrayal": -3, "betray": -3, "bewildering": -2, "bliss": 3, "blissful": 3,
    "blossom": 2, "boring": -2, "brave": 2, "bravery": 2, "break": -1,
    "breakthrough": 3, "bright": 2, "brilliant": 4, "brutal": -3, "brutality": -3,
    "bullied": -2, "bully": -2, "burden": -2, "calm": 2, "capable": 2,
    "care": 2, "cared": 2, "careful": 1, "careless": -2, "catastrophe": -3,
    "celebrate": 3, "celebration": 3, "challenge": 1, "chaos": -2, "charm": 3,
    "charming": 3, "cheat": -3, "cheerful": 3, "cheerfully": 3, "cheerfulness": 3,
    "clarify": 1, "clean": 2, "clumsy": -1, "cold": -1, "comfort": 2,
    "comfortable": 2, "compassion": 3, "compassionate": 3, "competent": 2, "complain": -2,
    "confident": 2, "confusion": -2, "congratulate": 3, "corrupt": -3, "courage": 2,
    "courageous": 2, "creative": 2, "crime": -3, "criminal": -3, "crisis": -2,
    "cruel": -3, "cruelty": -3, "curious": 1, "danger": -2, "dangerous": -2,
    "daring": 2, "deadlock": -2, "death": -2, "deceit": -3, "deceive": -3,
    "dedicated": 2, "defeat": -2, "defect": -2, "degrading": -2, "dejected": -2,
    "delay": -1, "delightful": 3, "deny": -1, "depressed": -2, "depression": -2,
    "desperate": -2, "despicable": -3, "destroy": -3, "destructive": -3, "determined": 2,
    "devastated": -3, "devastating": -3, "devoted": 3, "devotion": 3, "difficult": -1,
    "dirty": -2, "disagree": -2, "disappoint": -2, "disappointed": -2, "disappointing": -2,
    "disaster": -3, "discomfort": -2, "discouraged": -2, "dishonest": -3, "disorganized": -2,
    "distress": -3, "disturbing": -3, "dominate": -1, "doubt": -1, "dreadful": -3,
    "eager": 2, "easy": 1, "effective": 2, "efficient": 2, "empathy": 2,
    "encourage": 2, "encouraging": 2, "endure": 1, "energetic": 2, "enjoy": 3,
    "enjoyable": 3, "enjoyment": 3, "enlighten": 2, "enthusiasm": 3, "excellent": 3,
    "excitement": 3, "exciting": 3, "exhausted": -2, "fail": -2, "failure": -2,
    "faithful": 2, "fame": 2, "fantastic": 4, "fear": -2, "fearful": -2,
    "fierce": -1, "forgive": 2, "fraud": -3, "free": 1, "friendly": 3,
    "frightened": -2, "frustrated": -2, "frustration": -2, "fun": 3, "funny": 3,
    "gentle": 2, "glad": 3, "glory": 3, "good": 3, "graceful": 2,
    "grateful": 3, "gratitude": 3, "great": 3, "grief": -3, "grow": 2,
    "growth": 2, "guilty": -2, "happiness": 3, "happy": 3, "hard": -1,
    "harm": -2, "harmful": -2, "hate": -3, "helpless": -2, "heroic": 3,
    "hesitant": -1, "honest": 2, "hope": 2, "hopeful": 2, "hopeless": -2,
    "horrible": -3, "horrifying": -3, "hostility": -3, "humble": 2, "hurt": -2,
    "ideal": 2, "ignorant": -2, "ignorance": -2, "illusion": -1, "impressive": 3,
    "inadequate": -2, "incompetent": -2, "incredible": 4, "indifferent": -1, "inefficient": -2,
    "injustice": -3, "innovation": 2, "inspire": 3, "inspired": 3, "inspirational": 3,
    "insult": -2, "insulted": -2, "integrity": 2, "intelligent": 2, "intimidate": -2,
    "joyful": 3, "joyous": 3, "jubilant": 3, "kind": 2, "kindness": 3,
    "knowledge": 1, "lazy": -2, "learn": 1, "like": 2, "love": 3,
    "loyal": 2, "luck": 2, "magnificent": 4, "manipulate": -2, "meaningful": 2,
    "mediocre": -1, "melancholy": -2, "miserable": -3, "motivate": 2, "motivated": 2,
    "negative": -2, "neglect": -2, "nervous": -1, "offensive": -2, "oppose": -1,
    "optimistic": 2, "outstanding": 4, "overcome": 2, "overwhelmed": -2, "passionate": 3,
    "patience": 2, "peaceful": 3, "pessimistic": -2, "positive": 2, "powerful": 3,
    "prejudice": -2, "pride": 2, "problem": -1, "productive": 2, "progress": 2,
    "protect": 2, "proud": 2, "purposeful": 2, "quality": 2, "refuse": -1,
    "regret": -2, "reject": -2, "reliable": 2, "remarkable": 3, "resilient": 2,
    "respect": 2, "responsibility": 1, "restore": 2, "ruin": -3, "sad": -2,
    "selfish": -2, "shame": -2, "shock": -1, "sincere": 2, "skill": 2,
    "smart": 2, "sorrow": -2, "stable": 1, "strength": 2, "stress": -2,
    "struggle": -2, "success": 3, "suffer": -2, "suffering": -3, "support": 2,
    "terrible": -3, "thankful": 3, "thoughtful": 2, "together": 1, "tolerance": 1,
    "toxic": -3, "trust": 2, "truthful": 2, "uncertain": -1, "unfair": -2,
    "unique": 2, "upset": -2, "valuable": 2, "victorious": 3, "violence": -3,
    "vulnerable": -2, "warmth": 2, "weak": -1, "wisdom": 2, "wonderful": 4,
    "worry": -2, "worthless": -2, "wrong": -2, "zealous": 2
};

// Word suggestions for negative words
const wordSuggestions = {
    "abandon": { synonyms: ["maintain", "support", "keep"], rephrasing: ["continue with", "stay committed to"], ai: ["persist with", "follow through on"] },
    "abandoned": { synonyms: ["cared for", "supported", "maintained"], rephrasing: ["looked after", "kept up"], ai: ["sustained", "attended to"] },
    "abhor": { synonyms: ["admire", "respect", "love"], rephrasing: ["strongly dislike", "find disagreeable"], ai: ["feel aversion toward", "find distasteful"] },
    "abuse": { synonyms: ["care", "support", "kindness"], rephrasing: ["mistreat", "take advantage of"], ai: ["maltreatment", "harmful behavior"] },
    "abused": { synonyms: ["cared for", "supported", "respected"], rephrasing: ["mistreated", "exploited"], ai: ["maltreated", "harmed"] },
    "accused": { synonyms: ["cleared", "vindicated"], rephrasing: ["alleged to have", "suspected of"], ai: ["charged with", "claimed to be responsible for"] },
    "anger": { synonyms: ["calm", "peace", "serenity"], rephrasing: ["strong displeasure", "emotional frustration"], ai: ["heated frustration", "intense displeasure"] },
    "angry": { synonyms: ["calm", "composed", "serene"], rephrasing: ["upset", "displeased", "irritated"], ai: ["strongly displeased", "emotionally frustrated"] },
    "anxious": { synonyms: ["calm", "confident", "relaxed"], rephrasing: ["worried", "stressed", "uneasy"], ai: ["apprehensive", "on edge"] },
    "awful": { synonyms: ["wonderful", "great", "excellent"], rephrasing: ["very bad", "dreadful", "unpleasant"], ai: ["deeply unsatisfactory", "of very poor quality"] },
    "bad": { synonyms: ["good", "positive", "beneficial"], rephrasing: ["unsatisfactory", "poor", "inadequate"], ai: ["below expectations", "of concern"] },
    "betrayal": { synonyms: ["loyalty", "trust", "fidelity"], rephrasing: ["breach of trust", "act of disloyalty"], ai: ["violation of confidence", "broken promise"] },
    "boring": { synonyms: ["engaging", "interesting", "exciting"], rephrasing: ["monotonous", "unengaging"], ai: ["lacking stimulation", "uninspiring"] },
    "burden": { synonyms: ["relief", "support", "help"], rephrasing: ["heavy responsibility", "difficult challenge"], ai: ["demanding obligation", "challenging commitment"] },
    "careless": { synonyms: ["careful", "attentive", "diligent"], rephrasing: ["inattentive", "negligent"], ai: ["lacking due care", "insufficiently attentive"] },
    "corrupt": { synonyms: ["honest", "ethical", "upright"], rephrasing: ["dishonest", "unethical"], ai: ["acting without integrity", "engaging in misconduct"] },
    "cruel": { synonyms: ["kind", "compassionate", "gentle"], rephrasing: ["unkind", "harsh", "merciless"], ai: ["causing unnecessary suffering", "without compassion"] },
    "dangerous": { synonyms: ["safe", "harmless", "secure"], rephrasing: ["poses a risk", "potentially harmful"], ai: ["presents significant risk", "could cause harm"] },
    "deceive": { synonyms: ["honest", "truthful", "sincere"], rephrasing: ["mislead", "misrepresent"], ai: ["provide false information", "act dishonestly"] },
    "depressed": { synonyms: ["happy", "uplifted", "content"], rephrasing: ["feeling low", "experiencing sadness"], ai: ["experiencing emotional difficulty", "struggling with mood"] },
    "destroy": { synonyms: ["build", "create", "protect"], rephrasing: ["cause damage to", "ruin"], ai: ["cause irreparable harm to", "demolish"] },
    "disappointed": { synonyms: ["satisfied", "pleased", "content"], rephrasing: ["let down", "unfulfilled"], ai: ["found lacking", "fell short of expectations"] },
    "fail": { synonyms: ["succeed", "achieve", "accomplish"], rephrasing: ["did not achieve", "fell short"], ai: ["did not meet the target", "encountered challenges"] },
    "fear": { synonyms: ["courage", "bravery", "confidence"], rephrasing: ["concern about", "worry regarding"], ai: ["apprehension about", "sense of unease toward"] },
    "frustrated": { synonyms: ["satisfied", "content", "fulfilled"], rephrasing: ["feeling blocked", "experiencing difficulty"], ai: ["encountering impediments", "finding progress difficult"] },
    "hate": { synonyms: ["love", "appreciate", "value"], rephrasing: ["strongly dislike", "have an aversion to"], ai: ["find deeply unpleasant", "have strong negative feelings toward"] },
    "harmful": { synonyms: ["beneficial", "helpful", "safe"], rephrasing: ["damaging", "detrimental"], ai: ["causing adverse effects", "posing a risk"] },
    "horrible": { synonyms: ["wonderful", "excellent", "great"], rephrasing: ["very unpleasant", "dreadful"], ai: ["deeply unsatisfactory", "extremely poor"] },
    "hostile": { synonyms: ["friendly", "welcoming", "warm"], rephrasing: ["aggressive", "antagonistic"], ai: ["openly oppositional", "combative"] },
    "ignorant": { synonyms: ["knowledgeable", "aware", "informed"], rephrasing: ["uninformed", "unaware"], ai: ["lacking information about", "not yet informed on"] },
    "inadequate": { synonyms: ["sufficient", "adequate", "capable"], rephrasing: ["not enough", "insufficient"], ai: ["falling short of requirements", "below the needed standard"] },
    "insult": { synonyms: ["compliment", "praise", "commend"], rephrasing: ["offense", "disrespectful remark"], ai: ["disparaging comment", "derogatory statement"] },
    "lazy": { synonyms: ["energetic", "diligent", "hardworking"], rephrasing: ["unmotivated", "lacking initiative"], ai: ["disinclined to effort", "insufficiently proactive"] },
    "manipulate": { synonyms: ["support", "empower", "guide"], rephrasing: ["control unfairly", "influence improperly"], ai: ["exploit for personal gain", "exert undue influence over"] },
    "miserable": { synonyms: ["happy", "joyful", "content"], rephrasing: ["very unhappy", "deeply sad"], ai: ["experiencing significant distress", "profoundly discontented"] },
    "neglect": { synonyms: ["care", "tend to", "support"], rephrasing: ["fail to care for", "leave unattended"], ai: ["give insufficient attention to", "fail in duty of care for"] },
    "offensive": { synonyms: ["respectful", "kind", "pleasant"], rephrasing: ["inappropriate", "hurtful"], ai: ["causing discomfort", "considered disrespectful"] },
    "overwhelming": { synonyms: ["manageable", "simple", "easy"], rephrasing: ["a lot to handle", "very demanding"], ai: ["presenting significant demands", "requiring substantial effort"] },
    "pessimistic": { synonyms: ["optimistic", "hopeful", "positive"], rephrasing: ["expecting the worst", "negative outlook"], ai: ["expecting unfavorable outcomes", "viewing with skepticism"] },
    "prejudice": { synonyms: ["fairness", "objectivity", "impartiality"], rephrasing: ["bias", "unfair assumption"], ai: ["preconceived judgment", "unfounded assumption"] },
    "regret": { synonyms: ["joy", "satisfaction", "pride"], rephrasing: ["feel sorry about", "wish had been different"], ai: ["reflect with remorse on", "acknowledge as a misstep"] },
    "reject": { synonyms: ["accept", "welcome", "embrace"], rephrasing: ["decline", "not accept"], ai: ["decide against", "determine unsuitable"] },
    "ruin": { synonyms: ["build", "create", "restore"], rephrasing: ["cause damage to", "destroy"], ai: ["severely damage", "reduce to an unworkable state"] },
    "sad": { synonyms: ["happy", "joyful", "cheerful"], rephrasing: ["unhappy", "feeling down", "upset"], ai: ["experiencing sadness", "emotionally affected"] },
    "selfish": { synonyms: ["generous", "giving", "caring"], rephrasing: ["self-focused", "inconsiderate of others"], ai: ["prioritizing self over others", "lacking consideration"] },
    "shame": { synonyms: ["pride", "dignity", "honor"], rephrasing: ["embarrassment", "sense of guilt"], ai: ["feeling of dishonor", "self-reproach"] },
    "stress": { synonyms: ["calm", "relaxation", "ease"], rephrasing: ["pressure", "tension", "strain"], ai: ["significant demand on resources", "high-pressure situation"] },
    "struggle": { synonyms: ["succeed", "thrive", "flourish"], rephrasing: ["face difficulty", "have a hard time"], ai: ["encounter significant challenges", "experience hardship"] },
    "terrible": { synonyms: ["wonderful", "great", "excellent"], rephrasing: ["very bad", "dreadful"], ai: ["extremely unsatisfactory", "of very poor quality"] },
    "toxic": { synonyms: ["healthy", "safe", "beneficial"], rephrasing: ["harmful", "damaging"], ai: ["having a destructive effect", "creating a negative environment"] },
    "unfair": { synonyms: ["fair", "just", "equitable"], rephrasing: ["unjust", "biased", "one-sided"], ai: ["not equitable", "lacking impartiality"] },
    "upset": { synonyms: ["calm", "content", "pleased"], rephrasing: ["disturbed", "troubled", "distressed"], ai: ["experiencing emotional discomfort", "feeling unsettled"] },
    "violence": { synonyms: ["peace", "calm", "harmony"], rephrasing: ["harmful behavior", "aggressive action"], ai: ["use of force", "causing physical harm"] },
    "vulnerable": { synonyms: ["strong", "resilient", "protected"], rephrasing: ["exposed to risk", "in a fragile state"], ai: ["susceptible to harm", "in need of protection"] },
    "weak": { synonyms: ["strong", "capable", "powerful"], rephrasing: ["lacking strength", "not robust"], ai: ["requiring additional support", "not at full capacity"] },
    "worry": { synonyms: ["confidence", "calm", "assurance"], rephrasing: ["concern about", "be anxious about"], ai: ["feel apprehension about", "experience unease over"] },
    "worthless": { synonyms: ["valuable", "important", "worthwhile"], rephrasing: ["without value", "of no use"], ai: ["not contributing meaningfully", "lacking perceived value"] },
    "wrong": { synonyms: ["right", "correct", "accurate"], rephrasing: ["incorrect", "mistaken", "inaccurate"], ai: ["not as expected", "requiring correction"] }
};
