# Custom configuration file to enhance the visual appeal of the Streamlit App

[theme]
primaryColor="#4A90E2" # Blue for primary elements
backgroundColor="#F0F2F6" # Light gray background
secondaryBackgroundColor="#FFFFFF" # White for sidebars/boxes
textColor="#333333" # Dark text
font="sans serif"

[server]
# Allows the app to run smoothly in the cloud environment
enableCORS = true
enableXsrfProtection = false
